# Generated by Django 2.0.1 on 2018-06-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontos',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
