# Generated by Django 2.0.1 on 2018-06-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('pontos', '0002_auto_20180605_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontos',
            name='atracoes',
            field=models.ManyToManyField(to='atracoes.Atracoes'),
        ),
    ]
