# Generated by Django 2.0.1 on 2018-06-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0003_pontos_atracoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontos',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Aprovado'),
        ),
    ]
