# Generated by Django 2.0.1 on 2018-06-06 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0001_initial'),
        ('pontos', '0006_pontos_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontos',
            name='localizcao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localizacao.Localizacao'),
        ),
    ]
