# Generated by Django 2.0.1 on 2018-06-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0002_atracoes_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracoes',
            name='observacoes',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='OBS'),
        ),
    ]
